# Generated by Django 6.0.7 on 2026-07-28 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('paypal_id', models.CharField(blank=True, help_text='Null until PayPal has answered the create call.', max_length=64, null=True, unique=True)),
                ('request_id', models.CharField(blank=True, help_text='PayPal-Request-Id used to create this order.', max_length=128, null=True, unique=True)),
                ('intent', models.CharField(choices=[('CAPTURE', 'Capture'), ('AUTHORIZE', 'Authorize')], default='CAPTURE', max_length=16)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated locally'), ('CREATED', 'Created'), ('SAVED', 'Saved'), ('APPROVED', 'Approved'), ('PAYER_ACTION_REQUIRED', 'Payer action required'), ('VOIDED', 'Voided'), ('COMPLETED', 'Completed')], default='INITIATED', max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('live', models.BooleanField(default=False, help_text='Environment this order belongs to. Sandbox and live rows must never be read as interchangeable.')),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'PayPal order',
                'verbose_name_plural': 'PayPal orders',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('request_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated locally'), ('COMPLETED', 'Completed'), ('DECLINED', 'Declined'), ('PENDING', 'Pending'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially refunded')], default='INITIATED', max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('final_capture', models.BooleanField(default=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captures', to='paypal_checkout.paypalorder')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='paypalorder',
            index=models.Index(fields=['content_type', 'object_id'], name='paypal_chec_content_ef209e_idx'),
        ),
        migrations.AddIndex(
            model_name='paypalorder',
            index=models.Index(fields=['status', 'live'], name='paypal_chec_status_1a7aac_idx'),
        ),
        migrations.AddIndex(
            model_name='capture',
            index=models.Index(fields=['status'], name='paypal_chec_status_476c34_idx'),
        ),
    ]
