# Generated by Django 6.0.7 on 2026-07-28 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypal_checkout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('request_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated locally'), ('CREATED', 'Created'), ('CAPTURED', 'Captured'), ('PARTIALLY_CAPTURED', 'Partially captured'), ('DENIED', 'Denied'), ('EXPIRED', 'Expired'), ('PENDING', 'Pending'), ('VOIDED', 'Voided')], default='INITIATED', max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('expires_at', models.DateTimeField(blank=True, help_text="PayPal's expiration_time for the hold.", null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='paypal_checkout.paypalorder')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='capture',
            name='authorization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='captures', to='paypal_checkout.authorization'),
        ),
        migrations.AddIndex(
            model_name='authorization',
            index=models.Index(fields=['status'], name='paypal_chec_status_22d4c0_idx'),
        ),
    ]
