# Generated by Django 6.0.7 on 2026-07-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypal_checkout', '0002_authorization_capture_authorization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(help_text="PayPal's event id — the dedupe key.", max_length=64, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('resource_type', models.CharField(blank=True, max_length=64)),
                ('summary', models.TextField(blank=True)),
                ('transmission_id', models.CharField(blank=True, max_length=64)),
                ('live', models.BooleanField(default=False)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(blank=True, help_text="PayPal's create_time for the event.", null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-received_at',),
                'indexes': [models.Index(fields=['processed_at'], name='paypal_chec_process_7a5dfa_idx')],
            },
        ),
    ]
