# Generated by Django 6.0.7 on 2026-07-28 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypal_checkout', '0003_webhookevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('request_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated locally'), ('COMPLETED', 'Completed'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='INITIATED', max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('note_to_payer', models.CharField(blank=True, max_length=255)),
                ('invoice_id', models.CharField(blank=True, max_length=127)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='paypal_checkout.capture')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status'], name='paypal_chec_status_604b1b_idx')],
            },
        ),
    ]
