# Generated by Django 6.0.7 on 2026-07-28 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('paypal_checkout', '0004_refund'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('request_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('name', models.CharField(max_length=127)),
                ('product_type', models.CharField(choices=[('PHYSICAL', 'Physical goods'), ('DIGITAL', 'Digital goods'), ('SERVICE', 'Service')], default='SERVICE', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('live', models.BooleanField(default=False)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('request_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('product_paypal_id', models.CharField(blank=True, max_length=64)),
                ('name', models.CharField(max_length=127)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated locally'), ('CREATED', 'Created'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='INITIATED', max_length=24)),
                ('live', models.BooleanField(default=False)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, help_text='Null when the plan bills a product that is not in the local catalog.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='paypal_checkout.product')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('paypal_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('request_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('plan_paypal_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated locally'), ('APPROVAL_PENDING', 'Approval pending'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='INITIATED', max_length=24)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('subscriber_email', models.EmailField(blank=True, max_length=254)),
                ('custom_id', models.CharField(blank=True, max_length=127)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('next_billing_at', models.DateTimeField(blank=True, null=True)),
                ('live', models.BooleanField(default=False)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('plan', models.ForeignKey(blank=True, help_text='Null when subscribing to a plan that is not in the local catalog.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='paypal_checkout.plan')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_id', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('PENDING', 'Pending'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially refunded'), ('DENIED', 'Denied'), ('FAILED', 'Failed')], default='COMPLETED', max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='paypal_checkout.subscription')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['status', 'live'], name='paypal_chec_status_5eafb9_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['content_type', 'object_id'], name='paypal_chec_content_120ede_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'live'], name='paypal_chec_status_4cd4a4_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionpayment',
            index=models.Index(fields=['status'], name='paypal_chec_status_c61c7d_idx'),
        ),
    ]
