# Generated by Django 6.0.7 on 2026-07-29 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('paypal_checkout', '0005_product_plan_subscription_subscriptionpayment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetupToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('paypal_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('request_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated locally'), ('CREATED', 'Created'), ('PAYER_ACTION_REQUIRED', 'Payer action required'), ('APPROVED', 'Approved'), ('VAULTED', 'Vaulted'), ('TOKENIZED', 'Tokenized')], default='INITIATED', max_length=32)),
                ('customer_id', models.CharField(blank=True, max_length=64)),
                ('merchant_customer_id', models.CharField(blank=True, max_length=255)),
                ('payment_source_type', models.CharField(blank=True, max_length=32)),
                ('live', models.BooleanField(default=False)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PaymentToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('paypal_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('request_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated locally'), ('ACTIVE', 'Active'), ('DELETION_PENDING', 'Deletion pending'), ('DELETED', 'Deleted')], default='INITIATED', max_length=32)),
                ('customer_id', models.CharField(blank=True, max_length=64)),
                ('merchant_customer_id', models.CharField(blank=True, max_length=255)),
                ('payment_source_type', models.CharField(blank=True, max_length=32)),
                ('live', models.BooleanField(default=False)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('setup_token', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_token', to='paypal_checkout.setuptoken')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='setuptoken',
            index=models.Index(fields=['content_type', 'object_id'], name='paypal_chec_content_a692fa_idx'),
        ),
        migrations.AddIndex(
            model_name='setuptoken',
            index=models.Index(fields=['status', 'live'], name='paypal_chec_status_84fad0_idx'),
        ),
        migrations.AddIndex(
            model_name='setuptoken',
            index=models.Index(fields=['customer_id', 'live'], name='paypal_chec_custome_03d440_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttoken',
            index=models.Index(fields=['content_type', 'object_id'], name='paypal_chec_content_372aa3_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttoken',
            index=models.Index(fields=['status', 'live'], name='paypal_chec_status_aee6a1_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttoken',
            index=models.Index(fields=['customer_id', 'live'], name='paypal_chec_custome_da6960_idx'),
        ),
    ]
