# Generated by Django 6.0.7 on 2026-07-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paypal_checkout", "0006_setuptoken_paymenttoken_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="refund",
            name="merge_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="refund",
            name="sent_body",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="refund",
            name="status",
            field=models.CharField(
                choices=[
                    ("INITIATED", "Initiated locally"),
                    ("UNRESOLVED", "Unresolved"),
                    ("COMPLETED", "Completed"),
                    ("PENDING", "Pending"),
                    ("CANCELLED", "Cancelled"),
                    ("FAILED", "Failed"),
                ],
                default="INITIATED",
                max_length=24,
            ),
        ),
    ]
